-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 11:11:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cooper_flights
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cooper_flights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cooper_flights` DEFAULT CHARACTER SET utf8 ;
USE `cooper_flights` ;

-- -----------------------------------------------------
-- Table `cooper_flights`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooper_flights`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `suburb` VARCHAR(75) NOT NULL,
  `state` VARCHAR(3) NOT NULL,
  `postcode` INT NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooper_flights`.`plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooper_flights`.`plane` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `seating` INT NOT NULL,
  `last_serviced` DATE NOT NULL,
  `max_baggage_weight` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooper_flights`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooper_flights`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flight_number` VARCHAR(15) NOT NULL,
  `from_airport` VARCHAR(100) NOT NULL,
  `to_airport` VARCHAR(100) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `flight_datetime` DATETIME NOT NULL,
  `plane` INT NOT NULL,
  `distance_km` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `plane_foreign_key_idx` (`plane` ASC),
  CONSTRAINT `plane_foreign_key`
    FOREIGN KEY (`plane`)
    REFERENCES `cooper_flights`.`plane` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cooper_flights`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooper_flights`.`booking` (
  `id` INT NOT NULL,
  `flight_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `checkedin` TINYINT NULL DEFAULT 0,
  `checkin_datetime` DATETIME NULL,
  `booking_datetime` DATETIME NOT NULL,
  `baggage` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `flight_foreign_key_idx` (`flight_id` ASC),
  INDEX `customer_foreign_key_idx` (`customer_id` ASC),
  CONSTRAINT `flight_foreign_key`
    FOREIGN KEY (`flight_id`)
    REFERENCES `cooper_flights`.`flight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `customer_foreign_key`
    FOREIGN KEY (`customer_id`)
    REFERENCES `cooper_flights`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cooper_flights`.`plane`
-- -----------------------------------------------------
START TRANSACTION;
USE `cooper_flights`;
INSERT INTO `cooper_flights`.`plane` (`id`, `name`, `seating`, `last_serviced`, `max_baggage_weight`) VALUES (1, 'Cessna Citation Mustang', 4, '2018-10-04', 75);
INSERT INTO `cooper_flights`.`plane` (`id`, `name`, `seating`, `last_serviced`, `max_baggage_weight`) VALUES (2, 'Cessna CitationJet 525', 6, '2019-08-09', 150);
INSERT INTO `cooper_flights`.`plane` (`id`, `name`, `seating`, `last_serviced`, `max_baggage_weight`) VALUES (3, 'Embraer Phenom 100', 4, '2019-07-18', 100);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cooper_flights`.`flight`
-- -----------------------------------------------------
START TRANSACTION;
USE `cooper_flights`;
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (1, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-02 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (2, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-02 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (3, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-03 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (4, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-03 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (5, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-03 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (6, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-04 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (7, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-04 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (8, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-05 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (9, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-06 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (10, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-06 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (11, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-06 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (12, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-07 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (13, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-07 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (14, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-07 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (15, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-08 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (16, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-08 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (17, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-08 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (18, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-09 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (19, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-09 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (20, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-09 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (21, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-10 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (22, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-11 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (23, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-12 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (24, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-13 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (25, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-14 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (26, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-15 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (27, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-16 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (28, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-17 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (29, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-18 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (30, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-19 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (31, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-20 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (32, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-21 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (33, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-22 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (34, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-23 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (35, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-24 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (36, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-25 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (37, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-26 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (38, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-27 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (39, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-28 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (40, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-01-29 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (41, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-01-30 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (42, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-01-31 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (43, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-02-01 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (44, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-02-02 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (45, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-02-03 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (46, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-02-04 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (47, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-02-05 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (48, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-02-06 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (49, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-02-07 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (50, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-02-08 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (51, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-02-09 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (52, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-02-10 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (53, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-02-11 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (54, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-02-12 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (55, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-02-13 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (56, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-02-14 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (57, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-02-15 9:30am', 1, 777);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (58, 'QF1888', 'Cape York', 'Brisbane', 'Staged', '2020-02-16 12:30pm', 3, 2159);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (59, 'QF1769', 'Cape York', 'Darwin', 'Staged', '2020-02-17 5:30pm', 2, 1285);
INSERT INTO `cooper_flights`.`flight` (`id`, `flight_number`, `from_airport`, `to_airport`, `status`, `flight_datetime`, `plane`, `distance_km`) VALUES (60, 'QF1986', 'Cape York', 'Cairns', 'Staged', '2020-02-18 9:30am', 1, 777);

COMMIT;

